Add CSRF_SECRET_KEY to sample env var file.
The service will fail to start if the “CSRF_SECRET_KEY” environment variable is not in the `.env` file.

Log snippet:

```python
…
 File "/app/nginx_ldap_auth/app/main.py", line 87, in <module>

    @CsrfProtect.load_config

     ^^^^^^^^^^^^^^^^^^^^^^^

  File "/ve/lib/python3.13/site-packages/fastapi_csrf_protect/csrf_config.py", line 48, in load_config

    config = LoadConfig(**{key.lower(): value for key, value in settings()})

                                                                ~~~~~~~~^^

  File "/app/nginx_ldap_auth/app/main.py", line 89, in get_csrf_config

    return CsrfSettings()

  File "/ve/lib/python3.13/site-packages/pydantic_settings/main.py", line 176, in __init__

    super().__init__(

    ~~~~~~~~~~~~~~~~^

        **__pydantic_self__._settings_build_values(

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    ...<26 lines>...

        )

        ^

    )

    ^

  File "/ve/lib/python3.13/site-packages/pydantic/main.py", line 253, in __init__

    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)

pydantic_core._pydantic_core.ValidationError: 1 validation error for CsrfSettings

CSRF_SECRET_KEY

  Field required [type=missing, input_value={}, input_type=dict]

    For further information visit https://errors.pydantic.dev/2.11/v/missing⁠
```